name: flutter_image_preview
description: Modal image previewer
version: 0.1.1
repository: https://github.com/pedrofneves/flutter_image_preview

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: